version: 2.1

workflows:
  ci:
    jobs:
      - test_git
      
jobs:
  test_git:
    steps:
      - run:
          name: test
          command: |
            git config user.email "username@mydomain.com"
            git config user.name "My Name"
            echo "test" > test
            git add test
            git commit -m "test"
